### ISSUE TITLE
bug: SWAGGER 화면이 안 뜨고, JSON을 가져오지 못하는 오류

### ISSUE THREAD

**Issue by dalcheonroadhead** [6-SPOT/spot-BE#41]
# 1.BUG에 대해서 설명해주세요! 🐛 

SWAGGER를 설정했는데, 화면이 안 뜨고, JSON을 가져오지 못하는 오류를 겪었습니다.

# 2. 재현 하려면 어떻게 해야 하나요? 🤔
1. gradle 의존성
```gradle
implementation group: 'org.springdoc', name: 'springdoc-openapi-starter-webmvc-ui', version: '2.0.2'
```
2. Spring application.yml 설정
```yml
# SWAGGER
springdoc:
  show-login-endpoint: true
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    operations-sorter: alpha      # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    display-request-duration: true
    disable-swagger-default-url: true # petStore default로 들어가는 것 끄기
    urls:
      - name: "Default Server URL"
        url: "/api/v3/api-docs"

  default-produces-media-type: application/json
```
3. SwaggerConfig 
```java
package spot.spot.global.config;

import io.swagger.v3.oas.models.Components;
import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.security.SecurityRequirement;
import io.swagger.v3.oas.models.security.SecurityScheme;
import io.swagger.v3.oas.models.servers.Server;
import org.springdoc.core.models.GroupedOpenApi;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.http.HttpHeaders;
import spot.spot.global.ConstantUtil;

@Configuration
public class SwaggerConfig {

    @Bean
    public GroupedOpenApi api() {
        return GroupedOpenApi.builder()
            .group("all-api")
            .pathsToMatch("/**")
            .build();
    }

    @Bean
    public OpenAPI openAPI() {
        Info info = new Info()
            .title("SPOT - 어디든 간다. 무엇이든 한다.")
            .version("v0.0.1")
            .description("SPOT API 명세서.");

        SecurityScheme bearer = new SecurityScheme()
            .type(SecurityScheme.Type.HTTP)
            .scheme("bearer")
            .bearerFormat(ConstantUtil.AUTHORIZATION)
            .in(SecurityScheme.In.HEADER)
            .name(HttpHeaders.AUTHORIZATION);

        // Security 요청 설정
        SecurityRequirement addSecurityItem = new SecurityRequirement();
        addSecurityItem.addList(ConstantUtil.AUTHORIZATION);

        Components components = new Components()
            .addSecuritySchemes(ConstantUtil.AUTHORIZATION, bearer);

        return new OpenAPI()
            .components(components)
            .addSecurityItem(addSecurityItem)
            .addServersItem(new Server().url("https://ilmatch.net/api")
                .description("Default Server URL"))
            .addServersItem(new Server().url("http://localhost:8080/api")
                .description("Local Development Server"))
            .info(info)
            .components(components)
            .addSecurityItem(addSecurityItem);
    }
}
```

# 3. 어떤 에러를 마주했나요? 📜 
1.  `java.lang.NoClassDefFoundError: org/springframework/web/servlet/resource/LiteWebJarsResourceResolver` 발생 
2. `NoSuchMethodError`

# 4. ScreenShot 📷
![Image](https://github.com/user-attachments/assets/b28299e1-b401-46f7-ada5-8f68f93d8412)
